/**
 *
 */
package com.esis.italia.course.example.enumeration;

/**
 * @author Giampiero Cicala
 *
 */
public enum CallType {
	INSERTAZIENDA,DELETEAZIENDA,UPDATEAZIENDA,SELECTAZIENDA,
	INSERTDIPARTIMENTO,DELETEDIPARTIMENTO,UPDATEDIPARTIMENTO,SELECTDIPARTIMENTO,
	INSERTIMPIEGATO,DELETEIMPIEGATO,UPDATEIMPIEGATO,SELECTIMPIEGATO,
	INSERTMANSIONE,DELETEMANSIONE,UPDATEMANSIONE,SELECTMANSIONE,
	INSERTRUOLO,DELETERUOLO,UPDATERUOLO,SELECTRUOLO;
}
